name: annualreport2017
baseurl: /2017
host: 0.0.0.0
gems: ['jekyll/minibundle']
title: >
  Matthew’s Year in Review 2017
description: >
  Matthew is a part-time web developer for mySociety, part-time parent to a two-year old, part-time musician, full-time tired, in Birmingham, UK.
